'use client';
import {useEffect,useMemo,useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {BookOpen,CalendarDays,Users,Flag,Search,Shield,Sparkles,ExternalLink,Check,AlertCircle,Save,Swords,ChevronRight} from 'lucide-react';
import characters from '@/data/characters.json';
import seedRoster from '@/data/roster.json';
import seedNews from '@/data/news.json';
import guides from '@/data/guides.json';
import factionTeams from '@/data/faction-teams.json';
const STATIC=process.env.NEXT_PUBLIC_PAGES==='true';
const imagePath=(p:string)=>STATIC?'/Dragonsoul/public'+p:p;
type Character=typeof characters[number];
type Entry={owned:boolean,star:string,note:string,confirmed?:boolean};
type Roster=Record<string,Entry>;
const official='https://sod.game-beans.com/';
const byId=Object.fromEntries(characters.map(c=>[c.id,c]));
const stages=['待確認','金5','金6','紫1','紫2','紫3','紫4','紫5','紫6','紅1','紅2','紅3','紅4','紅5','紅6','鑽','神1','神2','神3','神4','神5'];
const teams={
 one:[{title:'主力推圖隊',label:'先用現有養成',ids:['57','36','18','91','93','2'],roles:['主坦／冰凍','副坦／輸出','主輸出','控制／護盾','增益／續航','增傷／干擾'],note:'保留瑪莉的既有投入，火槍集中輸出裝。睡神先以紫三為目標；莉莉絲未到紅一，依實戰與薇薇安輪替。',order:'手動先處理瑪莉必要的奧義，再接睡神與穗香、火槍；優先打斷敵方關鍵技能。',risk:'睡神奧義對非同陣營單位會加費，瑪莉吃不到同陣營完整增益。此隊用於一般主塔，不能直接進奧術陣營塔。'}],
 two:[{title:'第一隊・奧術主軸',label:'主要資源集中',ids:['57','18','91','93','2','28'],roles:['主坦','主輸出','控制／護盾','增益／續航','傷害增幅','石化／加費'],note:'讓冰坦、火槍、睡神與穗香保留完整核心；美杜莎以控制補前排壓力。',order:'先確保冰坦存活，穗香增益接火槍輸出；美杜莎手動石化危險目標。',risk:'僅一個專職坦克，前排撐不住時，改用海爾曼替換美杜莎；這是混隊，不代表奧術塔合法名單。'},
 {title:'第二隊・既有高星',label:'利用已投入角色',ids:['36','65','9','3','98','101'],roles:['前排／輸出','守護前排','刺客收割','刺客輸出','核心增益','續航／增益'],note:'瑪莉與奧伯隆妮保護隊伍，芬里爾、霞處理目標；薇薇安支援實際輸出最高的一人。',order:'先給主要輸出增益，再集中一個目標收割；勿平均分散火力。',risk:'偏近戰，遇到群控或開場爆發容易受限。作為第二隊過渡，不為此隊追加抽舊刺客。'}],
 three:[{title:'第一隊・睡神核心',label:'主隊保留完整',ids:['57','18','91','93','2','28'],roles:['主坦','主輸出','控制／護盾','增益／續航','傷害增幅','石化／加費'],note:'保持主要隊伍，裝備與升星仍先給這隊。',order:'控住高威脅目標，集中火槍輸出。',risk:'低星睡神與莉莉絲仍需生存配置，不能視為已成形的滿養成隊。'},
 {title:'第二隊・瑪莉帶隊',label:'過渡第二隊',ids:['36','65','9','3','98','101'],roles:['前排／輸出','守護前排','收割','單體輸出','增益','續航'],note:'沿用現有高星，不拆第一隊關鍵輔助。',order:'薇薇安支援主力，刺客集中同一目標。',risk:'適用對手與主隊不同；不保證在所有多隊玩法均有優勢。'},
 {title:'第三隊・功能過渡',label:'養成不足，先測試',ids:['64','67','76','72','88','104'],roles:['主坦','副坦／控制','法系輸出','法系輸出','元素配合','續航／前排增益'],note:'使用剩餘持有角色湊出雙前排、法傷與續航。玉藻前、宙斯目前投入不足，第三隊僅作過渡。',order:'先保住後排，觀察宙斯與玉藻前是否能完成技能循環。',risk:'這是避免重複角色的可試配置，不是成形的三隊畢業陣容。若第三隊太弱，優先保兩隊，別平均分散材料。'}]
};
const rosterIds=new Set(Object.keys(seedRoster));
function date(t:string){if(!t||Number.isNaN(Date.parse(t)))return t||'未定';return new Date(t).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});}
function Choice({value,onChange,options,label}:{value:string,onChange:(v:string)=>void,options:string[],label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(v=><SelectItem value={v} key={v}>{v}</SelectItem>)}</SelectContent></Select>}
export default function Home(){
 const [tab,setTab]=useState('roster'),[roster,setRoster]=useState<Roster>(seedRoster),[news,setNews]=useState(seedNews),[schedule,setSchedule]=useState({enabled:false,title:'每週四 21:00（台灣）',status:'尚未啟用'}),[error,setError]=useState(''),[query,setQuery]=useState(''),[job,setJob]=useState('全部職業'),[ownership,setOwnership]=useState('已記錄持有'),[detail,setDetail]=useState<Character|null>(null),[edit,setEdit]=useState<Entry>({owned:true,star:'待確認',note:''}),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState(''),[mode,setMode]=useState('one'),[guide,setGuide]=useState('圖鑑'),[faction,setFaction]=useState('奧術');
 useEffect(()=>{if(STATIC){try{const saved=localStorage.getItem('dragon-roster-v1');if(saved)setRoster(JSON.parse(saved))}catch{setError('瀏覽器持有資料無法讀取，暫用截圖快照。')}setSchedule({enabled:true,title:'每週四 21:00（台灣）',status:'公告排程更新'});fetch('./news.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<typeof seedNews>}).then(setNews).catch(()=>setError('目前顯示內建公告快照，最新公告暫時無法讀取。'));return;}fetch('/api/state').then(async r=>{if(!r.ok)throw Error();return r.json() as Promise<{roster:Roster,news:typeof seedNews,schedule:{enabled:boolean,title:string,status:string}}>}).then(d=>{setRoster(d.roster);setNews(d.news);setSchedule(d.schedule)}).catch(()=>setError('目前顯示 10/2 整理快照；雲端資料暫時無法讀取，重新整理可再試。'))},[]);
 useEffect(()=>{const doc=document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}};if(!doc.modelContext?.registerTool)return;const ac=new AbortController();try{doc.modelContext.registerTool({name:'show_team_plan',description:'切換到持有與配隊頁的一隊、兩隊或三隊配置；不修改角色持有資料。',inputSchema:{type:'object',properties:{count:{type:'integer',enum:[1,2,3]}},required:['count'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:{count:number})=>{if(![1,2,3].includes(input.count))throw Error('隊數必須為 1、2 或 3');setTab('roster');setMode(['one','two','three'][input.count-1]);return {count:input.count,teams:teams[['one','two','three'][input.count-1] as keyof typeof teams].map(t=>({title:t.title,characters:t.ids.map(id=>byId[id].name)}))}}},{signal:ac.signal})}catch{}return ()=>ac.abort()},[]);
 const ownedCount=Object.values(roster).filter(r=>r.owned).length;
 const filtered=useMemo(()=>characters.filter(c=>(job==='全部職業'||c.class===job)&&(c.name+c.alias+c.role).toLowerCase().includes(query.toLowerCase())&&(tab!=='roster'||ownership==='全部圖鑑'||(ownership==='已記錄持有'?roster[c.id]?.owned:!roster[c.id]))),[query,job,tab,ownership,roster]);
 function open(c:Character){setDetail(c);setEdit(roster[c.id]??{owned:true,star:'待確認',note:''});setSaveError('')}
 async function save(){if(!detail)return;setSaving(true);setSaveError('');try{if(STATIC){const next={...roster,[detail.id]:{...edit,confirmed:true}};localStorage.setItem('dragon-roster-v1',JSON.stringify(next));setRoster(next);setDetail(null);return;}const r=await fetch('/api/state',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:detail.id,...edit})});const d=await r.json() as {error?:string,roster:Roster};if(!r.ok)throw Error(d.error);setRoster(d.roster);setDetail(null)}catch(e){setSaveError(e instanceof Error?e.message:'未能儲存，請重試')}finally{setSaving(false)}}
 function card(c:Character,compact=false,role?:string){return <button key={c.id} className={'character '+(compact?'compact':'')} onClick={()=>open(c)}><div className="portrait"><img src={imagePath(c.portrait)} alt={c.name} loading="lazy"/><span className={'rank r'+c.variants.at(-1)?.tier.replace('+','plus')}>{c.variants.at(-1)?.tier}</span>{roster[c.id]?.owned&&<span className="owned-mark"><Check size={13}/></span>}</div><div className="char-text"><span className="char-title">{c.name.split(/[•・]/)[0].trim()}</span><strong>{c.short}</strong><span className="char-meta">{compact?role:c.class+' · '+c.factions.join('／')}</span><span className={'star '+(roster[c.id]?.star.startsWith('紅')?'redstar':'')}>{roster[c.id]?.owned?roster[c.id].star==='待確認'?'已持有 · 星級待確認':roster[c.id].star:roster[c.id]?'未持有':'持有待核對'}</span></div></button>}
 const active=mode==='factions'?[factionTeams.find(t=>t.faction===faction)!]:teams[mode as keyof typeof teams];
 return <div className="site-shell"><header className="topbar"><a href={STATIC?"/Dragonsoul/":"/"} className="brand"><span className="brand-gem">◇</span><span>龍魂旅人<small>作戰手帳</small></span></a><div className="top-right"><span className="server-tag">台服</span><a href="https://reurl.cc/rKOAXk" target="_blank" rel="noreferrer">原始表單 <ExternalLink size={14}/></a></div></header>
 <Tabs value={tab} onValueChange={v=>{setTab(v);setQuery('');setJob('全部職業')}} className="workspace"><aside className="sidebar"><p className="nav-label">我的攻略站</p><TabsList className="main-nav"><TabsTrigger value="guide"><BookOpen/>攻略資料庫</TabsTrigger><TabsTrigger value="news"><CalendarDays/>公告與卡池</TabsTrigger><TabsTrigger value="roster"><Users/>持有與配隊</TabsTrigger><TabsTrigger value="plan"><Flag/>補強與規劃</TabsTrigger></TabsList><div className="sidebar-note"><Sparkles size={19}/><strong>本期重點</strong><p>睡神先補功能門檻，保留已養成主力。</p><span>角色資料快照 2026.10.02</span></div><div className="source-credit">角色與圖像依據<br/>筱宮璃紗／MDM／佳里等<br/><a href="https://reurl.cc/rKOAXk" target="_blank" rel="noreferrer">全角色養成指南</a></div></aside>
 <main className="main-content">{error&&<p className="notice warning"><AlertCircle size={17}/>{error}</p>}
 <TabsContent value="roster"><div className="page-heading"><div><p className="eyebrow">YOUR FIELD TEAM</p><h1>持有角色與配隊</h1><p>保留主隊強度，再安排第二、第三隊。</p></div><span className="large-count">{ownedCount}<small>位已記錄持有</small></span></div>
 <div className="notice"><Check size={18}/><span>穗香截圖為紅一，已達表單最低門檻。星級看不清的角色保留待確認，點角色卡即可修正。</span></div>
 <Tabs value={mode} onValueChange={setMode}><div className="section-top"><h2><Swords size={20}/>推薦配隊</h2><TabsList className="mode-tabs"><TabsTrigger value="one">一隊集中</TabsTrigger><TabsTrigger value="two">兩隊配置</TabsTrigger><TabsTrigger value="three">三隊配置</TabsTrigger><TabsTrigger value="factions">六陣營配隊</TabsTrigger></TabsList></div>
 {mode==='factions'&&<><div className="faction-tabs" role="group" aria-label="選擇陣營">{factionTeams.map(t=><Button key={t.faction} variant={faction===t.faction?'default':'outline'} onClick={()=>setFaction(t.faction)}>{t.faction}</Button>)}</div><p className="caption">各隊六人皆具有該陣營標籤，依表單歸屬核對；雙陣營角色可跨分類出現。這是分別挑戰的陣營塔試用配置，不是同時出戰六隊。實際入場規則仍以遊戲為準。</p></>}<div className="team-stack">{active.map((t,i)=><section className="team-panel" key={t.title}><div className="team-heading"><div><span className="team-num">0{i+1}</span><h3>{t.title}</h3></div><span className={'pill '+(i===2?'amber':'')}>{t.label}</span></div><div className="team-grid">{t.ids.map((id,j)=>card(byId[id],true,t.roles[j]))}</div><p className="team-note">{t.note}</p>{mode==='factions'&&<div className="faction-alts"><strong>同陣營替補池</strong><p className="caption">依職業替換：前排倒下先補坦克；超時再換輸出。未記錄持有的角色不會冒充已持有。</p><div className="team-grid">{characters.filter(c=>c.factions.includes(faction)&&roster[c.id]?.owned&&!t.ids.includes(c.id)).map(c=>card(c,true,c.class))}</div></div>}<details><summary>站位、操作與限制 <ChevronRight size={15}/></summary><div className="detail-notes"><p><b>位置：</b>坦克承受主要火力，輸出與牧師放安全位置；對位依關卡調整。</p><p><b>操作：</b>{t.order}</p><p><b>限制：</b>{t.risk}</p>{t.ids.some(id=>!roster[id]?.owned)&&<p className="warning-text">此配置有角色被標記未持有／待核對，請先核對角色卡；配置未自動換人。</p>}</div></details></section>)}</div></Tabs>
 <p className="caption">配隊為依現有名單提出的試用方案；同一模式中角色不重複。三隊模式代表能組出的過渡配置，並非三隊都已達畢業強度。</p>
 {STATIC&&<div className="notice"><Save size={18}/><span>持有與星級只儲存在這個瀏覽器，換裝置不會自動同步。請定期匯出備份。</span><Button variant="outline" onClick={()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(roster,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='dragon-roster.json';a.click();URL.revokeObjectURL(u)}}>匯出持有</Button><label className="outline-link">匯入備份<input type="file" accept="application/json" hidden onChange={async e=>{try{const f=e.target.files?.[0];if(!f)return;const d=JSON.parse(await f.text());if(!d||typeof d!=='object'||Array.isArray(d)||!Object.entries(d).every(([id,v])=>{const x=v as Entry;return !!byId[id]&&x&&typeof x.owned==='boolean'&&stages.includes(x.star)&&typeof x.note==='string'&&x.note.length<=500}))throw Error();localStorage.setItem('dragon-roster-v1',JSON.stringify(d));setRoster(d);setError('')}catch{setError('匯入失敗，請使用本站匯出的有效持有備份。')}e.target.value=''}}/></label></div>}<div className="section-top roster-title"><h2>我的角色庫</h2><span className="muted">點擊卡片查看與修正</span></div><div className="filters"><div className="searchbox"><Search size={18}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜尋角色或暱稱" aria-label="搜尋持有角色"/></div><Choice label="持有狀態" value={ownership} onChange={setOwnership} options={['已記錄持有','尚未核對','全部圖鑑']}/><Choice label="職業" value={job} onChange={setJob} options={['全部職業','刺客','射手','戰士','坦克','法師','牧師']}/></div><div className="character-grid">{filtered.map(c=>card(c))}</div>{!filtered.length&&<p className="empty">沒有符合條件的角色，請調整搜尋或篩選。</p>}<p className="caption">「尚未核對」不代表沒有持有。來源圖片為表單原皮，與你的服裝外觀可能不同。</p></TabsContent>
 <TabsContent value="guide"><div className="page-heading"><div><p className="eyebrow">FIELD GUIDE</p><h1>攻略資料庫</h1><p>101 位角色，按職業、體系與養成條件閱讀。</p></div><a className="outline-link" href="https://reurl.cc/rKOAXk" target="_blank" rel="noreferrer">開啟原表 <ExternalLink size={15}/></a></div><Tabs value={guide} onValueChange={setGuide}><TabsList className="guide-tabs"><TabsTrigger value="圖鑑">角色圖鑑</TabsTrigger><TabsTrigger value="分項攻略">分項攻略</TabsTrigger><TabsTrigger value="原始表單">原始表單</TabsTrigger></TabsList><TabsContent value="圖鑑"><div className="tier-legend"><span><b>SS</b> 通用頂尖</span><span><b>S+</b> 體系核心</span><span><b>S</b> 合適隊伍強角</span><span><b>A+ 以下</b> 看用途與成本</span></div><div className="filters"><div className="searchbox"><Search size={18}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜尋名字、暱稱或定位" aria-label="搜尋全角色"/></div><Choice label="圖鑑職業" value={job} onChange={setJob} options={['全部職業','刺客','射手','戰士','坦克','法師','牧師']}/><span className="muted">{filtered.length} 位</span></div><div className="character-grid">{filtered.map(c=>card(c))}</div></TabsContent><TabsContent value="分項攻略"><div className="guide-grid">{guides.map(g=><section className="text-panel" key={g.title}><span className="eyebrow">{g.tag}</span><h2>{g.title}</h2><ul>{g.points.map(p=><li key={p}>{p}</li>)}</ul></section>)}</div><div className="text-panel"><h2>配隊閱讀順序</h2><p>先選主輸出與陣營，補坦克、續航及控制，再看增益是否能作用到核心。睡神偏奧術／幻境；花弓與浮士德須分開看有無專武神三。單一 SS 角色不一定勝過合適的 S+ 體系成員。</p><p>表單偏後期 PVE，不把單一 TIER 當成每個帳號的抽卡順序。每個角色詳細頁保留原表舊評與新備註，方便檢查版本差異。</p></div></TabsContent><TabsContent value="原始表單"><div className="text-panel"><h2>原作者完整表單</h2><p>保留原始來源方便核對。若內嵌表單無法顯示，可在新分頁開啟。</p><a className="outline-link" target="_blank" rel="noreferrer" href="https://reurl.cc/rKOAXk">開啟完整養成指南 <ExternalLink size={15}/></a><iframe title="龍魂旅人全角色養成指南原始表單" loading="lazy" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vREVRXcRDNRRKeVnVVseKgTcc4X5nHulX90S8CqalKqY_o85lrsOKPv2kA7SJvYgPNVNydzGU2aAMSl/pubhtml"/></div></TabsContent></Tabs></TabsContent>
 <TabsContent value="news"><div className="page-heading"><div><p className="eyebrow">TAIWAN SERVER INTELLIGENCE</p><h1>公告與後續卡池</h1><p>官方確認的活動，以及另行標示的預測。</p></div><a className="outline-link" href={official} target="_blank" rel="noreferrer">台服官網 <ExternalLink size={15}/></a></div><div className="update-bar"><CalendarDays size={22}/><div><strong>{schedule.title}</strong><p>{schedule.enabled?'已啟用定期更新':schedule.status} · 最近核對 {date(news.checkedAt)}</p></div></div><p className="news-summary">{news.summary}</p><h2 className="section-title">卡池時間軸</h2><div className="banner-grid">{news.banners.map(b=><article className="banner-card" key={b.name}>{byId[b.characterId]&&<img src={imagePath(byId[b.characterId].portrait)} alt={b.name}/>}<div><span className="pill">{Date.parse(b.end)<Date.now()?'已結束':b.status}</span><h3>{b.name}</h3><p className="date-range">{date(b.start)} — {date(b.end)}</p><p>{b.advice}</p><a href={b.url} target="_blank" rel="noreferrer">查看官方公告 <ExternalLink size={13}/></a></div></article>)}</div><div className="news-columns"><section><h2 className="section-title">官方公告</h2>{news.items.map(n=><article className="announcement" key={n.id}><span className="eyebrow">{n.date} · {n.category}</span><h3><a href={n.url} target="_blank" rel="noreferrer">{n.title} <ExternalLink size={15}/></a></h3><p>{n.summary}</p></article>)}</section><section><h2 className="section-title">活動截止提醒</h2><div className="timeline">{news.events.map(e=><article key={e.title}><time>{date(e.end)}</time><strong>{e.title}</strong><p>{e.note}</p></article>)}</div></section></div><div className="text-panel"><h2>後續檔期・尚未確認</h2>{news.future.map(f=><p key={f.date+f.title}><span className="pill amber">{f.status}</span> <b>{f.date} · {f.title}</b><br/>{f.note}</p>)}<p className="caption">表單推測不等於台服官方排程；不以陸服日期推定台服日期。</p></div></TabsContent>
 <TabsContent value="plan"><div className="page-heading"><div><p className="eyebrow">NEXT INVESTMENT</p><h1>補強與後續規劃</h1><p>先跨過功能門檻，再提高整隊上限。</p></div><span className="pill amber">鑽石截圖：2,780</span></div><div className="plan-lead"><Flag size={28}/><div><h2>本期：睡神紫三，限定資源集中一人</h2><p>穗香若確認為紅一，先停止追最低門檻；莉莉絲紅一與主力輸出的補強，再依剩餘資源擇一。</p></div></div><div className="priority-list">{[{id:'91',target:'第一優先 · 紫三',title:'睡神補功能門檻',text:'先做心魔與免費戰令，把現有碎片、鈴蘭、池內階段獎勵合計；紫三後再評估紅一。',stop:'達紫三先測試，不為稱號硬追。'},{id:'93',target:'已到門檻 · 紅一',title:'穗香先用現有養成',text:'截圖紅一已達作者最低需求；與睡神同隊，先處理急速、減費與生存。',stop:'若持有頁修正了星級，請重新計算此目標。'},{id:'2',target:'下一個限定目標 · 紅一',title:'莉莉絲集中補強',text:'目前紫一，補到紅一比同時開多隻新角更容易規劃。資源不足就存，不分散小抽。',stop:'只補一個功能門檻，暫不追鑽。'},{id:'18',target:'主力輸出 · 裝備優先',title:'火槍鞏固奧術輸出',text:'目前紅一先上場，集中較好的輸出裝。等第一隊循環穩定，再考慮更高星。',stop:'先提升實際傷害，不因榜單推薦鑽就立刻追。'},{id:'15',target:'後續神話目標 · 紫三',title:'月神留到下一階段',text:'目前金六。睡神完成前先不拆神話資源；有預算再規劃月神紫三作輔助。',stop:'不依未確認的新神話日期提前押注。'}].map((p,i)=><article key={p.id}><span className="priority-num">0{i+1}</span><button className="plan-face" onClick={()=>open(byId[p.id])}><img src={imagePath(byId[p.id].portrait)} alt={byId[p.id].name}/></button><div><span className="eyebrow">{p.target}</span><h3>{p.title}</h3><p>{p.text}</p><span className="stop-rule">停手點：{p.stop}</span></div></article>)}</div><div className="guide-grid"><section className="text-panel"><h2>這期先保留的資源</h2><ul><li>神話券與鈴蘭：集中睡神，下一期再回存。</li><li>限定券：先比較莉莉絲紅一的差額，避免同時追瑪莉、冰坦上鑽。</li><li>山銅、神輝：暫不開花弓或浮士德的神三專武線。</li><li>琥珀：決定職業用途後再重置。</li></ul><p className="caption">背包圖示尚未確認券種，2,780 鑽不能直接換算為可追幾星。</p></section><section className="text-panel"><h2>300 神話券不是紅一保證</h2><p>示例：300 抽約 270 碎片，階段 60、心魔 36，共 366 片可合成 6 本體；約 3,600 鈴蘭保底再換 1 本體。約 7 本體是模型估值，仍有隨機性與起始庫存差異。</p><p>零積分時 2,050 鈴蘭為一個祈願本體保底預算；已有積分則減少。實際追加量以活動畫面核對。</p></section></div><div className="text-panel"><h2>接下來的執行節奏</h2><ol><li>10/2～10/5：每日免費十連、心魔與戰令；測試主隊。</li><li>10/7 晚間：復刻追加最後決策，巴別塔 22:00 前完成排名。</li><li>10/8～10/10：中秋登入與兌換收尾，限定資源開始回存。</li><li>10/11～10/14：結算睡神的碎片與鈴蘭，只补差額。</li><li>10/15 起：儲備下一階段資源，依新公告調整。</li></ol><p className="caption">此規劃依 2026/10/2 持有快照。每週公告自動更新，個人星級需由你修正；公告更新不會擅自改動你的持有名單。</p></div></TabsContent>
 <footer>台服攻略整理 · 角色評價與圖片出處：<a href="https://reurl.cc/rKOAXk" target="_blank" rel="noreferrer">全角色養成指南</a> · 官方資訊以公告原文為準。</footer></main></Tabs>
 <Dialog open={!!detail} onOpenChange={v=>{if(!v)setDetail(null)}}><DialogContent className="character-dialog">{detail&&<><DialogTitle>{detail.name}</DialogTitle><DialogDescription>{detail.class} · {detail.factions.join('／')} · 原皮對照，外觀可能不同</DialogDescription><div className="dialog-profile"><img src={imagePath(detail.portrait)} alt={detail.name}/><div><span className="pill">{detail.quality}</span><p>{detail.alias}</p><strong>{detail.role||'原表未填定位'}</strong></div></div><div className="dialog-scroll">{detail.variants.map((v,i)=><section className="variant" key={i}><h3>{v.specialist?'專武版本':'一般版本'} <span className="rank-inline">{v.tier}</span></h3><p><b>養成門檻：</b>{v.requirement||'原表未填'}</p><p><b>配裝：</b>{v.equipment||'依用途調整'}</p><p><b>主塔／PVP：</b>{v.tower||'未填'}／{v.pvp||'未填'}</p>{v.newNote&&<p><b>最新備註：</b>{v.newNote}</p>}{v.oldNote&&<details><summary>原表舊評（可能保留舊版本）</summary><p>{v.oldNote}</p></details>}</section>)}<section className="edit-roster"><h3>我的持有狀態</h3><div className="edit-controls"><Choice label="是否持有" value={edit.owned?'已持有':'未持有'} onChange={v=>setEdit({...edit,owned:v==='已持有'})} options={['已持有','未持有']}/><Choice label="角色星級" value={edit.star} onChange={v=>setEdit({...edit,star:v})} options={stages}/></div><label htmlFor="note">備註</label><Input id="note" value={edit.note} onChange={e=>setEdit({...edit,note:e.target.value})} maxLength={500}/>{saveError&&<p className="warning-text" role="alert">{saveError}</p>}<Button className="save-button" onClick={save} disabled={saving}><Save size={16}/>{saving?'儲存中…':'儲存持有資料'}</Button></section></div></>}</DialogContent></Dialog></div>
}
